//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoffeDate
    {
        public int Id { get; set; }
        public string Time { get; set; }
        public Nullable<int> Passed { get; set; }
        public string ShoutId { get; set; }
        public string ShoutPrice { get; set; }
        public string Venue { get; set; }
    }
}
